dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.0'


dotenv: '.env'
wallets:
  from_key: ${PRIVATE_KEY}